shop/apps/cart/urls.py
# -*- coding: utf-8 -*-
"""
@Time    : 2020/3/22 15:59
@Author  : 半纸梁
@File    : urls.py
"""
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('index/', views.CartIndexView.as_view(), name="index"),
    path('add/', views.AddCartView.as_view(), name="add"),
    path('edit/<int:goods_id>/', views.CartEditView.as_view(), name="update"),

]

shop/apps/goods/urls.py
# -*- coding: utf-8 -*-
"""
@Time    : 2020/3/22 15:59
@Author  : 半纸梁
@File    : urls.py
"""
from django.urls import path
from goods import views

app_name = "goods"
urlpatterns = [
    path('index/', views.GoodsIndexView.as_view(), name="index"),
    path('detail/<int:goods_id>', views.GoodsDetailView.as_view(), name="detail"),
    path('list/<int:type_id>/<int:page>/', views.GoodsTypeListView.as_view(), name="list"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('user/', include('user.urls')),
    path('goods/', include('goods.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('search/',include('haystack.urls')),

]

shop/apps/goods/models.py
# -*-coding:utf-8-*-
from django.db import models
from utils.base_model.base_model import BaseModel
from tinymce.models import HTMLField


class GoodsType(BaseModel):
    """商品类型模型类"""
    name = models.CharField(max_length=20, verbose_name='商品种类名称', help_text="商品种类名称")
    logo = models.CharField(max_length=20, verbose_name='类型logo', help_text="类型logo")
    image = models.URLField(default="", verbose_name='商品类型图片', help_text="商品类型图片")

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_goods_type'
        verbose_name = '商品种类'
        verbose_name_plural = verbose_name


    def __str__(self):
        return self.name


class GoodsSKU(BaseModel):
    """商品SKU模型类"""
    status_choices = (
        (0, '下线'),
        (1, '上线')
    )
    type = models.ForeignKey('GoodsType', on_delete=models.SET_NULL, null=True, verbose_name='商品种类')
    goods = models.ForeignKey('Goods', on_delete=models.SET_NULL, null=True, verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='商品名称', help_text="商品名称")
    desc = models.CharField(max_length=256, verbose_name='商品简介', help_text="商品简介")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='价格', help_text="价格")
    unite = models.CharField(max_length=20, verbose_name='商品单位', help_text="商品单位")
    image = models.URLField(default='', verbose_name='商品图片', help_text="商品图片")
    stock = models.IntegerField(default=1, verbose_name='商品库存', help_text="商品库存")
    sales = models.IntegerField(default=0, verbose_name='商品销量', help_text="商品销量'")
    status = models.SmallIntegerField(default=1, choices=status_choices, verbose_name='状态', help_text="状态")

    class Meta:
        ordering = ['sales', '-update_time', '-id']
        db_table = 'tb_goods_sku'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Goods(BaseModel):
    """商品SPU模型类"""
    name = models.CharField(max_length=20, verbose_name='商品SPU名称', help_text="商品SPU名称")
    # 富文本类型：带有格式的文本
    detail = HTMLField(blank=True, verbose_name='商品详情', help_text="商品详情")

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_goods'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class IndexGoodsBanner(BaseModel):
    """首页轮播商品展示模型类"""
    PRI_CHOICE = [
        (1, "第一级"),
        (2, "第二级"),
        (3, "第三级"),
        (4, "第四级"),

    ]
    sku = models.ForeignKey('GoodsSKU', on_delete=models.CASCADE, verbose_name='商品', )
    image = models.URLField(default='', verbose_name='图片', help_text="图片")
    priority = models.IntegerField(default=4, choices=PRI_CHOICE,verbose_name='展示顺序', help_text="展示顺序")

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_index_banner'
        verbose_name = '首页轮播商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexTypeGoodsBanner(BaseModel):
    """首页分类商品展示模型类"""
    DISPLAY_TYPE_CHOICES = (
        (0, '标题'),
        (1, '图片')
    )
    PRI_CHOICE = [
        (1, "第一级"),
        (2, "第二级"),
        (3, "第三级"),
        (4, "第四级"),
    ]

    type = models.ForeignKey('GoodsType', on_delete=models.CASCADE, verbose_name='商品类型')
    sku = models.ForeignKey('GoodsSKU', on_delete=models.CASCADE, verbose_name='商品SKU')
    display_type = models.SmallIntegerField(default=1, choices=DISPLAY_TYPE_CHOICES, verbose_name='展示类型',
                                            help_text="展示类型")
    priority = models.IntegerField(default=4, choices=PRI_CHOICE,verbose_name='展示顺序', help_text="展示顺序")

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_index_type_goods'
        verbose_name = '主页分类展示商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexPromotionBanner(BaseModel):
    """轮播图促销活动模型类"""
    PRI_CHOICES = [
        (1, "第一级"),
        (2, "第二级"),
        (3, "第三级"),
        (4, "第四级"),
        (5, "第五级"),
        (6, "第六级"),
    ]
    name = models.CharField(max_length=20, verbose_name='活动名称', help_text="活动名称")
    url = models.URLField(verbose_name='活动链接', help_text="活动链接")
    image = models.URLField(default='', verbose_name='活动图片', help_text="活动图片")
    priority = models.IntegerField(default=6, choices=PRI_CHOICES, verbose_name="优先级", help_text="优先级")

    class Meta:
        ordering = ['priority', '-update_time', '-id']
        db_table = 'tb_index_promotion'
        verbose_name = '主页促销活动'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsComments(BaseModel):
    """
    create news comments models
    field:
        content
        author
        news
        parent
    """
    content = models.TextField(verbose_name="评论内容", help_text="评论内容")
    user = models.ForeignKey("user.User", on_delete=models.SET_NULL, null=True)
    goods = models.ForeignKey("GoodsSKU", on_delete=models.CASCADE)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)  # 自我关联，多级评论，blank允许前端不传数据

    class Meta:
        ordering = ["-update_time", "-id"]
        db_table = "tb_goods_comments"
        verbose_name = "评论内容"
        verbose_name_plural = verbose_name

    def get_comment_count(self):
        return

    # 自定义字典转化
    def to_dict_data(self):
        comment_dict_data = {
            "comment_id": self.id,  # 评论id
            "goods_id": self.goods.id,  # 商品id
            "content": self.content,  # 评论内容
            "update_time": self.update_time.strftime("%Y年%m月%d日"),  # 更新日期
            "user": self.user.username,  # 评论人
            "parent": self.parent.to_dict_data() if self.parent else None  # 二级评论
        }

        return comment_dict_data

    def __str__(self):
        return "评论内容：{}".format(self.content)

shop/apps/goods/views.py
import json

from django.views import View
from django.urls import reverse
from django.core.cache import cache
from django.core.paginator import Paginator
from django_redis import get_redis_connection
from django.shortcuts import render, redirect
from haystack.views import  SearchView

from goods import contains

from celery_tasks.static_html.tasks import get_index_static_html
from goods.models import GoodsSKU, IndexGoodsBanner, GoodsType, IndexPromotionBanner, GoodsComments


class GoodsIndexView(View):
    """商品主页"""

    def get(self, request):
        """
        商品类型，商品轮播图，商品促销轮播图，商品信息这些保存到缓存中，这部分所有人看到的都是一样的
        :param request:
        :return:
        """
        # １．先判断是否已经缓存
        context = {}
        # context = cache.get("index_static_data")
        if not context:
            # 商品类型
            goods_types = GoodsType.objects.only("id", "name", "logo").filter(is_delete=False).order_by("id")

            # 商品主页轮播图
            index_banners = IndexGoodsBanner.objects.only("image", "sku__goods__id").filter(is_delete=False).order_by(
                "priority")

            # 商品促销轮播图
            pro_banners = IndexPromotionBanner.objects.only("url", "image").filter(is_delete=False).order_by("priority")

            for goods_type in goods_types:
                good_sku_obj = GoodsSKU.objects.only("image").filter(is_delete=False, type_id=goods_type.id).order_by(
                    "-update_time")[:4]
                goods_type.good_sku_obj = good_sku_obj

            context = {
                "goods_types": goods_types,
                "index_banners": index_banners,
                "pro_banners": pro_banners,
            }
            # 2.设置缓存
            # key，value，timeout = DEFAULT_TIMEOUT
            cache.set("index_static_data", context, timeout=1)  # 秒为单位

        # 判断用户是否已经登录
        cart_count = 0
        user = request.user
        if user.is_authenticated:
            # 获取购物车中的数量
            redis_conn = get_redis_connection("cart")
            re_key = "cart_{}".format(user.id)
            cart_count = redis_conn.hlen(re_key)
        context.update(cart_count=cart_count)

        return render(request, 'goods/index.html', context=context)


class GoodsDetailView(View):
    """商品详情"""

    def get(self, request, goods_id):

        # 1.查询到id=goods_id的商品信息
        try:
            goods = GoodsSKU.objects.only().filter(is_delete=False, id=goods_id).first()

        except GoodsSKU.DoesNotExist:  # 如果商品不存在就重定向到主页面
            return redirect(reverse("goods:index"))

        # 2. 获取到新品：获取同类型的最前面的两个产品,同时不包括上面的产品呢
        new_goods_rec = GoodsSKU.objects.only("image", "price", "name"). \
                            filter(is_delete=False, type=goods.type).exclude(id=goods.id).order_by("-create_time")[:2]

        # 获取同种类的不同规格的SPU商品
        same_goods = GoodsSKU.objects.only("name").filter(is_delete=False, goods=goods.goods).exclude(id=goods.id)

        # 4. 获取到评论
        comments = GoodsComments.objects.only().filter(is_delete=False, goods=goods.id)

        user = request.user
        if user.is_authenticated:
            # 获取商品浏览历史记录
            his_conn = get_redis_connection("history")
            his_key = "history_{}".format(request.user.id)
            # 判断列表中是否已经有了该商品
            his_conn.lrem(his_key, 0, goods.id)  # 移除浏览记录该商品
            his_conn.lpush(his_key, goods.id)  # 左侧插入
            # 只保存5条的浏览记录
            his_conn.ltrim(his_key, 0, 4)

            # 获取购物车中的商品个数
            cart_conn = get_redis_connection("cart")
            cart_key = "cart_{}".format(request.user.id)

            cart_count = cart_conn.hget(cart_key, goods_id)
            # 如果不存在就将购物车数量s设定为0
            if not cart_count:
                cart_count = 0
            cart_count = int(cart_count)


        return render(request, 'goods/detail.html', locals())


class GoodsTypeListView(View):
    """
    类型商品展示列表
    """

    def get(self, request, type_id, page):
        try:
            type = GoodsType.objects.only().filter(id=type_id, is_delete=False).first()
        except GoodsType.DoesNotExist:
            return redirect(reverse("goods:index"))

        sort = request.GET.get("sort")
        if sort == "price":  # 价格排序
            goods = GoodsSKU.objects.only().filter(is_delete=False, type=type).order_by("price")
        elif sort == "sales":  # 销量排序
            goods = GoodsSKU.objects.only().filter(is_delete=False, type=type).order_by("sales")
        elif sort == "time":  # 上架时间排序
            goods = GoodsSKU.objects.only().filter(is_delete=False, type=type).order_by("create_time")
        elif sort == "comments":  # 评论数
            goods = GoodsSKU.objects.only().filter(is_delete=False, type=type).order_by("goodscomments__goods")
        else:
            sort = "default"  # id排序
            goods = GoodsSKU.objects.only().filter(is_delete=False, type=type).order_by("id")

        # 创建分页对象
        pagin = Paginator(goods, contains.PER_PAGE_NUMBER)

        # 获取到页数
        try:
            page = int(page)
        except Exception as e:
            page = 1

        if page > pagin.num_pages:  # 判读传来的页码数是否大于最大页码数
            page = pagin.num_pages  # 直接最大页

        goods_data = pagin.page(page)  # 分页对象
        # 2. 获取到新品：获取同类型的最前面的两个产品,同时不包括上面的产品呢
        new_goods_rec = GoodsSKU.objects.only("image", "price", "name"). \
                            filter(is_delete=False, type=type).order_by("-create_time")[:2]

        user = request.user
        cart_count = 0
        if user.is_authenticated:
            redis_conn = get_redis_connection("default")
            re_key = "cart_id_{}".format(user.id)
            cart_count = redis_conn.hlen(re_key)

        context = {
            "type": type,
            "new_goods_rec": new_goods_rec,
            "goods_data": goods_data,
            "sort": sort,
        }
        context.update(cart_count=cart_count)
        return render(request, 'goods/list.html', context=context)



class Search(SearchView):
    pass
    template ="goods/search"

shop/templates/goods/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base/base.html' %}
{# 网页主体内容块 #}
{% block content %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class = "{{ type.logo }}">{{ type.name}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页 列表页 主体内容块 #}
{#    {% block content %}{% endblock  %}#}
{% endblock  %}

shop/templates/goods/detail.html
{% extends 'goods/base_detail_list.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-商品详情{% endblock%}

{% block content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ goods.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ goods.image }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.name }}</h3>
			<p>{{ goods.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.price }}</em></span>
				<span class="show_unit">单  位：{{ goods.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
            <div>
                <div>其他规格:</div>
                <div>
                    {% for goods in same_goods %}
                        <a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a>
                    {% endfor %}
                </div>
            </div>
			<div class="total">总价：<em>{{ goods.price }}元</em></div>
            {% csrf_token %}
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart"  data-sku-id="{{ goods.id }}"  id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_goods in new_goods_rec %}
					<li>
						<a href="{% url 'goods:detail' new_goods.id %}"><img src="{{ new_goods.image }}"></a>
						<h4><a href="{% url 'goods:detail' new_goods.id %}">{{ new_goods.name }}</a></h4>
						<div class="prize">￥{{ new_goods.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active" id="tag_detail"><a href="">商品介绍</a></li>
				<li id="tag_comment" data-goods-id="{{ goods.id }}"><a href="">评论</a></li>
			</ul>

			<div class="tab_content" id="tab_detail">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods.detail|safe }}</dd>
				</dl>
			</div>

            <div class="tab_content" id="tab_comment" style="display: none;">
				<dl>
                    {% for comment in comments %}
                        <dt>评论时间: {{ comment.update_time }} 用户名:{{ comment.user.username }}</dt>
                        <dd>评论内容: {{ comment.content }}</dd>
                    {% empty %}
                        暂时没有评论信息
                    {% endfor %}
				</dl>
			</div>

		</div>
	</div>
{% endblock%}
{% block bottom %}
	<div class="add_jump"></div>
{% endblock  %}

{% block script %}
    <script src="{% static 'js/goods/goods_detal.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base/message.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base/sweetalert.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base/jQuery_3.3.1.js' %}"></script>
    <script src="{% static 'js/base/csrf.js' %}"></script>
{% endblock  %}
{#{% block script %}#}
{#	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>#}
{#	<script type="text/javascript">#}
{#      // 商品介绍与评论tag的切换#}
{#      $('#tag_detail').click(function () {#}
{#          $('#tag_comment').removeClass('active')#}
{#          $(this).addClass('active')#}
{#          $('#tab_detail').show()#}
{#          $('#tab_comment').hide()#}
{#      })#}
{##}
{#      $('#tag_comment').click(function () {#}
{#          $('#tag_detail').removeClass('active')#}
{#          $(this).addClass('active')#}
{#          $('#tab_comment').show()#}
{#          $('#tab_detail').hide()#}
{#      })#}
{##}
{##}
{#       // 计算商品的小计#}
{#        function update_sku_amount() {#}
{#            count = $('.num_show').val();#}
{#            price = $('.show_pirze').children('em').text();#}
{#            // 计算小计#}
{#            amount = parseFloat(price) * parseInt(count);#}
{#            // 设置商品的小计#}
{#            $('.total').children('em').text(amount.toFixed(2)+'元');#}
{##}
{#        }#}
{#       // 商品数量增加#}
{#        $('.add').click(function () {#}
{#            // 获取商品的数量#}
{#            count = $('.num_show').val();#}
{#            // 增加1#}
{#            count = parseInt(count)+1;#}
{#            // 重新设置商品的数量#}
{#            $('.num_show').val(count);#}
{##}
{#            // 重新计算小计#}
{#            update_sku_amount()#}
{##}
{#        });#}
{#        // 商品数量减少#}
{#       $('.minus').click(function () {#}
{#           count = $('.num_show').val();#}
{#           count = parseInt(count)-1;#}
{#           if (count <= 0) {#}
{#               count = 1;#}
{#           }#}
{#           $('.num_show').val(count);#}
{##}
{#           update_sku_amount();#}
{#       });#}
{#       // 手动输入#}
{#       $('.num_show').blur(function () {#}
{#           count = $(this).val();#}
{#           // 校验count 是否合法#}
{#           if (isNaN(count) || count.trim().length == 0 || parseInt(count)<=0){#}
{#                count = 1;#}
{#           }#}
{#           $('.num_show').val(parseInt(count));#}
{#           update_sku_amount();#}
{#       });#}
{##}
{#		// 获取add_cart a标签左上角的坐标#}
{#		var $add_x = $('#add_cart').offset().top;#}
{#		var $add_y = $('#add_cart').offset().left;#}
{##}
{#        // 获取show_count div元素左上角的坐标#}
{#		var $to_x = $('#show_count').offset().top;#}
{#		var $to_y = $('#show_count').offset().left;#}
{##}
{#			$('#add_cart').click(function(){#}
{#            // 获取商品id和商品数目#}
{#            count = $('.num_show').val()#}
{#            sku_id = $(this).attr('sku_id') // prop attr#}
{#            csrf = $('input[name="csrfmiddlewaretoken"]').val()#}
{#            // 组织参数#}
{#            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}#}
{#            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count#}
{#            $.post('{% url 'cart:add' %}', params, function (data) {#}
{#                if (data.res == 5){#}
{#                    // 添加成功#}
{#                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})#}
{#                    $(".add_jump").stop().animate({#}
{#                    'left': $to_y+7,#}
{#                    'top': $to_x+7},#}
{#                    "fast", function() {#}
{#                        $(".add_jump").fadeOut('fast',function(){#}
{#                            // 重新设置用户购物车中商品的条目数#}
{#                            $('#show_count').html(data.cart_count);#}
{#                        });#}
{#			        });#}
{#                }#}
{#                else{#}
{#                    alert(data.errmsg)#}
{#                }#}
{#            })#}
{##}
{#		})#}
{#	</script>#}
{#{% endblock %}#}

shop/templates/goods/index.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}天天生鲜-首页{% endblock%}



{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in index_banner %}
                    <li><a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banner %}
			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {# 首页展示分类文字商品信息 #}
                {% for banner in type.title_banner %}
                    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banner %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock %}

shop/templates/goods/list.html
{% extends 'goods/base_detail_list.html' %}

{% block title %}
    天天生鲜-商品列表
{% endblock title %}

{% block content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_goods in new_goods_rec %}
					<li>
						<a href="{% url 'goods:detail' new_goods.id %}"><img src="{{ new_goods.image }}"></a>
						<h4><a href="{% url 'goods:detail' new_goods.id %}">{{ new_goods.name }}</a></h4>
						<div class="prize">￥{{ new_goods.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=sales" {% if sort == 'sales' %}class="active"{% endif %}>销量</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=comments" {% if sort == 'comments' %}class="active"{% endif %}>评论数</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=time" {% if sort == 'time' %}class="active"{% endif %}>上架时间</a>


			</div>

			<ul class="goods_type_list clearfix">
                {# {% for sku in skus_page.object_list %}  如下一样的#}
                {% for goods in goods_data %}
				<li>
					<a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image }}"></a>
					<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
					<div class="operate">
						<strong class="prize">￥{{ goods.price }}</strong>
                        <p class="desc">{{ goods.desc }}</p>
                        <p class="desc">已有<em>{{ goods.goodscomments.goods.length }}+</em>评价</p>
						<p class="unit">{{ goods.price }}/{{ goods.unite }}</p>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
            {# 有上一页 #}
                {% if goods_data.has_previous %}
                    <a href="{% url 'goods:list' type.id goods_data.previous_page_number%}?sort={{ sort }}">上一页</a>
                {% endif %}

            {% for page_num in goods_data.paginator.page_range %}
                {% if page_num == goods_data.number %}
                    <a href="{% url 'goods:list' type.id page_num %}?sort={{ sort }}" class="active">{{ page_num }}</a>
                {% else %}
                    <a href="{% url 'goods:list' type.id page_num %}?sort={{ sort }}">{{ page_num }}</a>
                {% endif %}
            {% endfor %}

            {# 有下一页 #}
            {% if goods_data.has_next %}
                <a href="{% url 'goods:list' type.id goods_data.next_page_number  %}?sort={{ sort }}">下一页</a>
            {% endif %}
            
			</div>
		</div>
	</div>
{% endblock  %}