shop/apps/goods/urls.py
# -*- coding: utf-8 -*-
"""
@Time    : 2020/3/22 15:59
@Author  : 半纸梁
@File    : urls.py
"""
from django.urls import path
from goods import views

app_name = "goods"
urlpatterns = [
    path('index/', views.GoodsIndexView.as_view(), name="index"),
    path('detail/<int:goods_id>', views.GoodsDetailView.as_view(), name="detail"),
    path('list/<int:type_id>/<int:page>/', views.GoodsTypeListView.as_view(), name="list"),
]

shop/apps/user/urls.py
# -*- coding: utf-8 -*-
"""
@Time    : 2020/3/22 15:59
@Author  : 半纸梁
@File    : urls.py
"""

from django.urls import path, re_path
from user import views

app_name = "user"
urlpatterns = [
    re_path("username/(?P<username>\w{5,20})/", views.CheckUsernameView.as_view(), name="username"),
    re_path("mobile/(?P<mobile>1[3-9]\d{9})/", views.CheckMobileView.as_view(), name="mobile"),
    path("sms_code/", views.SmsCodeView.as_view(), name="sms_code"),

    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),

    path('user_center/', views.UserCenterView.as_view(), name="user_center"),
    path('order/<int:page>/', views.UserOrderView.as_view(), name="order"),
    path('address/', views.ShippingAddressView.as_view(), name="address"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('user/', include('user.urls')),
    path('goods/', include('goods.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('search/',include('haystack.urls')),

]

shop/templates/static_base_html/static_base.html
{# 登录 注册 首页 #}
<!DOCTYPE>
<html lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题块 #}
	<title>
        {% block title %}{% endblock title %}
    </title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block link %}

    {% endblock %}
</head>
<body>

{# 网页顶部欢迎信息块 #}
{% block header %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center' %}">用户中心</a>
					<span>|</span>
					<a href="{#  #}">我的购物车</a>
{#                    {% url 'cart:show' %}#}
					<span>|</span>
					<a href="{#  #}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock%}

{# 网页搜索框块 #}
{% block search %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">

            </form>
		</div>

    {% block cart_bar %}
		<div class="guest_cart fr">
			<a href="{#  #}" class="cart_name fl">我的购物车</a>
            {% if cart_count %}
			    <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
            {% else %}
                <div class="goods_count fl" id="show_count">0</div>
            {% endif %}
		</div>
    {% endblock %}

	</div>
{% endblock %}



{# 网页主体内容块 #}
{% block content %}{% endblock %}

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2019-2020 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>

{% block script %}
{% endblock %}
</body>
</html>

shop/templates/static_base_html/static_index.html
{% extends 'static_base_html/static_base.html' %}
{% load staticfiles %}

{% block title %}天天生鲜-首页{% endblock%}
{% block link %}
<link rel="stylesheet" href="//at.alicdn.com/t/font_1720053_gl8y1m76ujm.css">
{% endblock %}



{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
        {# 商品分类 #}
		<ul class="subnav fl">
            {% for type in goods_types %}
                <li><a href=""><i class="iconfont {{ type.logo }}"></i>{{ type.name }}</a></li>
			{% endfor %}
		</ul>
        {# 分类轮播图 #}
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in index_banners %}
                    <li><a href="#"><img src="{{ banner.image }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>

    {# 促销轮播图 #}
		<div class="adv fl">
            {% for banner in pro_banners %}
			<a href="{{ banner.url }}"><img src="{{ banner.image }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in goods_types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="">{{ type.name }}</h3>
			<div class="subtitle fl">
                {# 定类轮播图 #}
                {% for banner in type.title_banner %}
                    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
{#			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>#}
        			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image}}"></div>
			<ul class="goods_list fl">
                {% for show_goods in type.good_sku_obj %}
				<li>
					<h4><a href="#">{{ show_goods.name }}</a></h4>
					<a href="#"><img src="{{ show_goods.image }}"></a>
					<div class="prize">¥ {{ show_goods.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock %}