shop/apps/cart/urls.py
# -*- coding: utf-8 -*-
"""
@Time    : 2020/3/22 15:59
@Author  : 半纸梁
@File    : urls.py
"""
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('index/', views.CartIndexView.as_view(), name="index"),
    path('add/', views.AddCartView.as_view(), name="add"),
    path('edit/<int:goods_id>/', views.CartEditView.as_view(), name="update"),

]

shop/apps/goods/urls.py
# -*- coding: utf-8 -*-
"""
@Time    : 2020/3/22 15:59
@Author  : 半纸梁
@File    : urls.py
"""
from django.urls import path
from goods import views

app_name = "goods"
urlpatterns = [
    path('index/', views.GoodsIndexView.as_view(), name="index"),
    path('detail/<int:goods_id>', views.GoodsDetailView.as_view(), name="detail"),
    path('list/<int:type_id>/<int:page>/', views.GoodsTypeListView.as_view(), name="list"),
]

shop/apps/user/urls.py
# -*- coding: utf-8 -*-
"""
@Time    : 2020/3/22 15:59
@Author  : 半纸梁
@File    : urls.py
"""

from django.urls import path, re_path
from user import views

app_name = "user"
urlpatterns = [
    re_path("username/(?P<username>\w{5,20})/", views.CheckUsernameView.as_view(), name="username"),
    re_path("mobile/(?P<mobile>1[3-9]\d{9})/", views.CheckMobileView.as_view(), name="mobile"),
    path("sms_code/", views.SmsCodeView.as_view(), name="sms_code"),

    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),

    path('user_center/', views.UserCenterView.as_view(), name="user_center"),
    path('order/<int:page>/', views.UserOrderView.as_view(), name="order"),
    path('address/', views.ShippingAddressView.as_view(), name="address"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('user/', include('user.urls')),
    path('goods/', include('goods.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('search/',include('haystack.urls')),

]

shop/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题块 #}
    <title>
        {% block title %}基类模板{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block link %}{% endblock %}

</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em><a href="">{{ user.username }}</a></em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user_center' %}">用户中心</a>
                    <span>|</span>
{#                    <a href="{% url 'cart:index' %}">我的购物车</a>#}
                    <span>|</span>
                    <a href="{% url 'user:order' 1 %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{# 网页搜索框块 #}
{% block search %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">

            </form>
        </div>

        {% block cart_bar %}
            <div class="guest_cart fr">
                <a href="" class="cart_name fl">我的购物车</a>
                {% if cart_count %}
                    <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
                {% else %}
                    <div class="goods_count fl" id="show_count">0</div>
                {% endif %}
            </div>
        {% endblock %}

    </div>
{% endblock %}



{# 网页主体内容块 #}
{% block content %}

{% endblock %}

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2019-2020 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>


<script src="{% static 'js/base/message.js' %}"></script>
<script src="{% static 'js/base/sweetalert.min.js' %}"></script>
<script src="{% static 'js/base/jQuery_3.3.1.js' %}"></script>
<script src="{% static 'js/base/csrf.js' %}"></script>

{% block script %}
{% endblock %}
</body>
</html>

shop/templates/base/base_no_cart.html
{# 购物车页面 提交订单页面 #}
{% extends 'base/base.html' %}
{% load staticfiles %}
{# 网页搜索框块 #}
{% block search_bar %}

	<div class="search_bar clearfix">

		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
            <form action="/search" method="get">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}

shop/templates/base/base_user_center.html
{# 用户中心-3个页面 #}
{% extends 'base/base.html' %}

{% block title %}
    用户中心
{% endblock title %}

{% block page_title %}
    用户中心
{% endblock %}


{% block cart_bar %}
{% endblock cart_bar %}

{% block content %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user_center' %}" class="active">· 个人信息</a></li>
                <li><a href="{% url 'user:order' 1 %}">· 全部订单</a></li>
                {#				<li><a href="" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>#}
                <li><a href="{% url 'user:address' %}">· 收货地址</a></li>
            </ul>
        </div>

        {# 用户中心-右侧内容块 #}
        {% block right_menu %}

        {% endblock %}
    </div>
{% endblock%}